#version 450

#extension GL_EXT_samplerless_texture_functions : require

layout(local_size_x = 8, local_size_y = 8) in;

layout(set = 0, binding = 0) uniform texture2D r_src;
layout(set = 0, binding = 1) writeonly uniform image2D r_dst;

layout(push_constant, std430)
uniform push_constant_t {
  ivec2 image_size;
};

void main() {
  ivec2 coord = ivec2(gl_GlobalInvocationID.xy);

  if (all(lessThan(coord, image_size)))
    imageStore(r_dst, coord, texelFetch(r_src, coord, 0));
}
